project:
  type: website
  output-dir: docs
  

website:
  title: "Hoomie studio"
  navbar:
    backgroundcolor: '#F7EEDD'
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - dashboard.qmd
      - note.qmd
      - 串接API教學筆記.qmd
      - maps.qmd
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    monofont: courier new
    editor: visual

      # - about.qmd
      # - maps.qmd
      
    
