---
title: "串接API教學筆記"
format: 
  html: # 注意這裡，html 後面有一個冒號，表示它是一個鍵，其值是下面的設定
    toc: true # 這是 table of content 目錄
    toc-location: left # 這是在左側的目錄
    number-sections: true # 對標題增加序號
    css: styles.css
editor: visual
---

## 導入必要的套件

::: {style="border: 1px solid black; padding: 10px;"}
**資料處理套件**
:::

```{r}
#| message: false
#| warning: false
library(readr) # 用於讀取 CSV 檔案
library(dplyr) #用於整理資料表的工具
```

::: {style="border: 1px solid black; padding: 10px;"}
**處理API套件**
:::

```{r}
#| message: false
#| warning: false
library(httr) # 用於處理 HTTP 請求的套件(爬蟲)
library(xml2) # 用於處理 XML 格式的資料
library(jsonlite) # 用於處理 JSON 格式的資料
library(rvest) #解析網頁內容的工具
```

::: {style="border: 1px solid black; padding: 10px;"}
**數據視覺化套件**
:::

```{r}
#| message: false
#| warning: false
library(ggplot2)  # 用於繪圖的套件
library(viridis) #用於色彩映射的工具
library(showtext) # 用於字體處理
library(plotly) # 把ggplot轉成互動式圖表html
```

## 測試資料集+資料清理

```{r}
#| message: false
#| warning: false
  formosa_massage <- read_csv("formosa_massage.csv")%>%  
  #head(10) %>% # 取前10筆資料 
  select(-服務) %>% # 排除 '服務項目' 欄位
  filter(longitude != 0 | latitude != 0) # 排除經緯度錯誤值
```

## 串接API查詢

::: {style="border: 1px solid black; padding: 10px;"}
**串接國土利用現況查詢**
:::

運作原理是只要修改API連結中的經緯度，就可以查詢不同地點的土地使用情況。 並且當中只要取想要的資料加到欄位例如`土地使用名稱`。 回傳的API是XML格式所以要用`xml2`套件來解析。

```{r}
for (i in 1:nrow(formosa_massage)) {
   lon <- formosa_massage$longitude[i]
   lat <- formosa_massage$latitude[i]
  landuse_url <- paste0("https://api.nlsc.gov.tw/other/LandUsePointQuery/", lon, "/", lat, "/", 4326)
  
# 發送 GET 請求
  response <- GET(landuse_url)
  
# 解析 XML 回應
  xml_content <- content(response, as = "text", encoding = "UTF-8")
  parsed_xml <- read_xml(xml_content)
  
# 提取所需的資訊 
  #土地類型 <- xml_find_first(parsed_xml, ".//Lname_C1")
  #land_use_value <- xml_text(土地類型)
  土地使用名稱 <- xml_find_first(parsed_xml, ".//NAME")%>%  xml_text() 
  
# 輸出結果
 #Sys.sleep(1) # 避免過於頻繁的請求
  formosa_massage$土地使用名稱[i] <- 土地使用名稱 # 將土地名稱存入dataframe中
 }
```

::: {style="border: 1px solid black; padding: 10px;"}
**串接縣市與行政區的API查詢**
:::

要根據API回傳格式制定要用甚麼套件處理，縣市行政區的API回傳格式是JSON，所以我們使用`jsonlite`套件來解析。

```{r}
for (i in 1:nrow(formosa_massage)) {
   lon <- formosa_massage$longitude[i]
   lat <- formosa_massage$latitude[i]
   admin_url <-  paste0("https://api.nlsc.gov.tw/other/TownVillagePointQuery1/", lon, "/", lat, "/", 4326)
   
   # 發送 GET 請求
   response <- GET(admin_url)
   
   # 解析 json 回應
   json_data <- content(response, "text", encoding = "UTF-8")
   parsed_json <- fromJSON(json_data) # <-- 這裡從 read_xml 改為 fromJSON
   
   
   # 提取所需的資訊 
   縣市 <-  parsed_json$ctyName
   行政區 <- parsed_json$townName
   
   # 輸出結果
   #Sys.sleep(1) # 避免過於頻繁的請求
   formosa_massage$縣市[i] <- 縣市 
   formosa_massage$行政區[i] <- 行政區 
 } 
```

## 串接查詢結果呈現

```{r}
 print(formosa_massage)
```

```{r}
ggplot(formosa_massage, aes(x = 縣市, fill = 土地使用名稱)) +
  geom_bar() +
  labs(title = "各縣市按摩店土地使用類型分布", x = "縣市", y = "數量") +
  scale_fill_viridis(discrete = TRUE) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```
